using EliasFM.ArtificialNeuralNet.Core;

// TODO: documentar os membros públicos restantes. Falta documentação

namespace EliasFM.ArtificialNeuralNet.CommonImplementation.Function;

/// <summary>
/// Activation function that blends a linear response with the hyperbolic tangent function, optionally followed by ReLU-style rectification.
///
/// The activation is computed as a weighted combination of:
/// - the original linear input,
/// - and the nonlinear tanh-compressed signal.
///
/// This design allows smooth interpolation between:
/// - purely nonlinear saturation,
/// - purely linear propagation,
/// - and hybrid behaviors.
///
/// Examples:
/// - linearFactor = 0, tanhFactor = 1:
///     pure tanh activation.
/// - linearFactor = 1, tanhFactor = 0:
///     pure linear activation.
/// - intermediate values:
///     blended response.
///
/// The rectified leak parameter controls how negative outputs are preserved:
/// - 0: hard rectification.
/// - 1: no rectification effect.
/// - values between 0 and 1: partial negative attenuation.
/// </summary>
public abstract class LinearTanhBlend : IActivation {

	/// <summary>
	/// Gets the contribution weight of the linear input component.
	///
	/// Higher values increase direct linear signal propagation.
	/// </summary>
	/// 
	public abstract double GetlinearFactor();

	/// <summary>
	/// Gets the contribution weight of the hyperbolic tangent component.
	///
	/// Higher values increase nonlinear saturation behavior.
	/// </summary>
	public abstract double GettanhFactor();

	/// <summary>
	/// Gets the leakage factor applied during rectification.
	///
	/// Controls how strongly negative outputs are preserved after blending.
	/// </summary>
	public virtual double GetRectifiedLeak() => 1;

	/// <summary>
	/// Computes the blended activation value.
	///
	/// The output is generated by combining:
	/// - a linear component,
	/// - a tanh-compressed nonlinear component,
	/// - and optional ReLU-style rectification.
	///
	/// </summary>
	/// <param name="x"> Input value. </param>
	/// <param name="linearFactor">
	/// Multiplicative factor applied to the linear input component.
	/// </param>
	/// <param name="tanhFactor">
	/// Multiplicative factor applied to the tanh component.
	/// </param>
	/// <param name="leak">
	/// Leakage factor used during rectification.
	/// </param>
	/// <returns> Activated output value. </returns>
	public static double Function(double x, double linearFactor, double tanhFactor, double leak = 0) {
		double tanh = Math.Tanh(x);
		return ReLU.Function(linearFactor * x + tanhFactor * tanh, leak);
	}

	/// <summary> Applies the activation using the current blend and rectification configuration. </summary>
	public double Apply(double input) => Function(input, GetlinearFactor(), GettanhFactor(), GetRectifiedLeak());

	public override string ToString() {
		return GetType().Name + '{' + $"Leak:{GetRectifiedLeak()}" + "," + $"linearFactor:{GetlinearFactor()}" + "," + $"tanhFactor:{GettanhFactor()}" + '}';
	}

	/// <summary>
	/// Creates a weighted LinearTanhBlend activation.
	///
	/// Returns a standard weighted blend when leak equals 1, otherwise returns a leaky weighted blend.
	/// </summary>
	public static Weighted Instantiate(double linearFactor, double tanhFactor, double leak = 1) {
		if (leak == 1) return new Weighted(linearFactor, tanhFactor);
		return new Weighted.Leaky(linearFactor, tanhFactor, leak);

	}

	/// <summary>
	/// Creates an interpolated LinearTanhBlend activation.
	///
	/// Returns a standard interpolated blend when leak equals 1, otherwise returns a leaky interpolated blend.
	/// </summary>
	public static Interpolated InstantiateInterpolated(double linearContribution, double leak = 1) {
		if (leak == 1) return new Interpolated(linearContribution);
		return new Interpolated.Leaky(linearContribution, leak);
	}

	#region subclasses
	/// <summary>
	/// Base variant of <see cref="LinearTanhBlend"/> with configurable
	/// rectification leakage.
	///
	/// Allows negative outputs to be partially preserved after rectification.
	/// </summary>
	public abstract class Leaky(double leak) : LinearTanhBlend {
		public double Leak { get; set; } = leak;
		public override double GetRectifiedLeak() => Leak;
	}

	/// <summary>
	/// LinearTanhBlend variant that interpolates between the linear and tanh components using complementary factors.
	///
	/// The tanh factor is always computed as:
	/// 1 - linearFactor
	///
	/// This creates a smooth transition between:
	/// - pure tanh behavior,
	/// - hybrid responses,
	/// - and pure linear propagation.
	///
	/// Examples:
	/// - linearFactor = 0:
	///     pure tanh.
	/// - linearFactor = 1:
	///     pure linear.
	/// </summary>
	public class Interpolated(double linearContribution) : LinearTanhBlend {
		/// <summary>
		/// Multiplicative factor applied to the linear component.
		///
		/// Increasing this value strengthens direct linear propagation
		/// while proportionally reducing tanh contribution.
		/// </summary>
		public double LinearFactor { get; set; } = linearContribution;

		/// <summary>
		/// Complementary factor applied to the tanh component.
		///
		/// This value is automatically derived from:
		/// 1 - linearFactor
		/// </summary>
		public double TanhFactor { get => 1 - LinearFactor; set { LinearFactor = 1 - value; } }
		public override double GetlinearFactor() { return LinearFactor; }
		public override double GettanhFactor() { return TanhFactor; }

		/// <summary>
		/// Interpolated LinearTanhBlend variant with configurable
		/// rectification leakage.
		///
		/// Combines complementary interpolation with partial
		/// preservation of negative outputs.
		/// </summary>
		public new class Leaky(double linearParticipation, double leak) : Interpolated(linearParticipation) {
			/// <summary>
			/// Leakage factor applied during rectification.
			/// </summary>
			public double Leak { get; set; } = leak;
			public override double GetRectifiedLeak() => Leak;
		}
	}

	/// <summary>
	/// LinearTanhBlend variant with independently configurable linear and tanh factors.
	///
	/// Unlike <see cref="Interpolated"/>, the factors are not complementary and may be adjusted separately.
	///
	/// This allows amplification, attenuation or arbitrary blending of both components.
	/// </summary>
	public class Weighted(double linearFactor = .5d, double tanhFactor = .5d) : LinearTanhBlend {
		/// <summary>
		/// Multiplicative factor applied to the linear component.
		/// </summary>
		public double LinearFactor { get; set; } = linearFactor;
		/// <summary>
		/// Multiplicative factor applied to the tanh component.
		/// </summary>
		public double TanhFactor { get; set; } = tanhFactor;
		public override double GetlinearFactor() => LinearFactor;
		public override double GettanhFactor() => TanhFactor;

		/// <summary>
		/// Weighted LinearTanhBlend variant with configurable
		/// rectification leakage.
		///
		/// Supports fully independent linear/tanh scaling
		/// combined with partial negative preservation.
		/// </summary>
		public new class Leaky(double leak, double linearFactor = .5d, double tanhFactor = .5d) : Weighted(linearFactor, tanhFactor) {
			/// <summary>
			/// Leakage factor applied during rectification.
			/// </summary>
			public double Leak { get; set; } = leak;
			public override double GetRectifiedLeak() => Leak;
		}
	}
	#endregion
}

